services:
  notification:
    build: notification
    restart: always
    ports:
      - 8082:8082
    networks:
      - spring-mysql
    depends_on:
      - product-service
  product-service:
    build: product-service
    restart: always
    ports:
      - 8081:8081
    networks:
      - spring-mysql
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/product_db?allowPublicKeyRetrieval=true
    depends_on:
      - db
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mysql:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_DATABASE=product_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springuser
      - MYSQL_ROOT_PASSWORD=springuser
    ports:
      - 3306:3306
    networks:
      - spring-mysql
networks:
  spring-mysql: